-- Customer Cohort Analysis

-- Let's Explore our Dataset First
USE SALES;

SELECT * FROM RETAIL LIMIT 10;

SELECT COUNT(*) FROM RETAIL; -- 521,773
SELECT * FROM RETAIL;

SELECT * FROM RETAIL
WHERE CUSTOMERID IS NULL
	OR CUSTOMERID = ''
    OR QUANTITY <= 0
    OR UNITPRICE = 0;
    
SELECT COUNT(*) FROM RETAIL
WHERE CUSTOMERID IS NULL
	OR CUSTOMERID = ''
    OR QUANTITY <= 0
    OR UNITPRICE = 0; -- 137,132 records have anomalies
    
SELECT * FROM RETAIL LIMIT 10;
-- ORDER BY INVOICEDATE DESC;
-- Let's start with the Cohort Analysis

CREATE OR REPLACE VIEW RETAIL_CLEANED AS
SELECT
	InvoiceNo,
    CustomerID,
    STR_TO_DATE(INVOICEDATE, '%m/%d/%Y %H:%i') as INVOICEDATE,
    ROUND(QUANTITY*UNITPRICE, 2) AS SALES
FROM RETAIL
WHERE CUSTOMERID IS NOT NULL
	AND CUSTOMERID != ''
    AND QUANTITY > 0
    AND UNITPRICE > 0;
    
-- Customer Retention
WITH CTE1 AS
(SELECT 
	CUSTOMERID,
    date_format(INVOICEDATE, '%Y-%m-01') AS PURCHASE_MONTH,
    date_format(MIN(INVOICEDATE) OVER(partition by CUSTOMERID ORDER BY INVOICEDATE), '%Y-%m-01') AS FIRST_TRANSACTION_MONTH
FROM RETAIL_CLEANED),

CTE2 AS
(SELECT 
	CUSTOMERID,
    FIRST_TRANSACTION_MONTH,
    PURCHASE_MONTH,
concat(
	'Month_',
    period_diff(
    EXTRACT(YEAR_MONTH FROM PURCHASE_MONTH),
    EXTRACT(YEAR_MONTH FROM FIRST_TRANSACTION_MONTH)
    )) AS COHORT_MONTH
FROM CTE1)

-- SELECT DISTINCT COHORT_MONTH FROM CTE2;
SELECT
	FIRST_TRANSACTION_MONTH AS COHORT,
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_0' THEN CUSTOMERID ELSE NULL END) AS "MONTH_0",
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_1' THEN CUSTOMERID ELSE NULL END) AS "MONTH_1",
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_2' THEN CUSTOMERID ELSE NULL END) AS "MONTH_2",
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_3' THEN CUSTOMERID ELSE NULL END) AS "MONTH_3",
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_4' THEN CUSTOMERID ELSE NULL END) AS "MONTH_4",
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_5' THEN CUSTOMERID ELSE NULL END) AS "MONTH_5",
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_6' THEN CUSTOMERID ELSE NULL END) AS "MONTH_6",
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_7' THEN CUSTOMERID ELSE NULL END) AS "MONTH_7",
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_8' THEN CUSTOMERID ELSE NULL END) AS "MONTH_8",
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_9' THEN CUSTOMERID ELSE NULL END) AS "MONTH_9",
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_10' THEN CUSTOMERID ELSE NULL END) AS "MONTH_10",
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_11' THEN CUSTOMERID ELSE NULL END) AS "MONTH_11",
    COUNT(DISTINCT CASE WHEN COHORT_MONTH = 'Month_12' THEN CUSTOMERID ELSE NULL END) AS "MONTH_12"
FROM CTE2
GROUP BY FIRST_TRANSACTION_MONTH
ORDER BY FIRST_TRANSACTION_MONTH;








-- Customer Lifetime Value
WITH CTE1 AS
(SELECT 
    SALES,
    date_format(INVOICEDATE, '%Y-%m-01') AS PURCHASE_MONTH,
    date_format(MIN(INVOICEDATE) OVER(partition by CUSTOMERID ORDER BY INVOICEDATE), '%Y-%m-01') AS FIRST_TRANSACTION_MONTH
FROM RETAIL_CLEANED),

CTE2 AS
(SELECT 
    SALES,
    FIRST_TRANSACTION_MONTH,
    PURCHASE_MONTH,
concat(
	'Month_',
    period_diff(
    EXTRACT(YEAR_MONTH FROM PURCHASE_MONTH),
    EXTRACT(YEAR_MONTH FROM FIRST_TRANSACTION_MONTH)
    )) AS COHORT_MONTH
FROM CTE1)

-- SELECT DISTINCT COHORT_MONTH FROM CTE2;
SELECT
	FIRST_TRANSACTION_MONTH AS COHORT,
    SUM(CASE WHEN COHORT_MONTH = 'Month_0' THEN SALES ELSE 0 END) AS "MONTH_0",
    SUM(CASE WHEN COHORT_MONTH = 'Month_1' THEN SALES ELSE 0 END) AS "MONTH_1",
    SUM(CASE WHEN COHORT_MONTH = 'Month_2' THEN SALES ELSE 0 END) AS "MONTH_2",
    SUM(CASE WHEN COHORT_MONTH = 'Month_3' THEN SALES ELSE 0 END) AS "MONTH_3",
    SUM(CASE WHEN COHORT_MONTH = 'Month_4' THEN SALES ELSE 0 END) AS "MONTH_4",
    SUM(CASE WHEN COHORT_MONTH = 'Month_5' THEN SALES ELSE 0 END) AS "MONTH_5",
    SUM(CASE WHEN COHORT_MONTH = 'Month_6' THEN SALES ELSE 0 END) AS "MONTH_6",
    SUM(CASE WHEN COHORT_MONTH = 'Month_7' THEN SALES ELSE 0 END) AS "MONTH_7",
    SUM(CASE WHEN COHORT_MONTH = 'Month_8' THEN SALES ELSE 0 END) AS "MONTH_8",
    SUM(CASE WHEN COHORT_MONTH = 'Month_9' THEN SALES ELSE 0 END) AS "MONTH_9",
    SUM(CASE WHEN COHORT_MONTH = 'Month_10' THEN SALES ELSE 0 END) AS "MONTH_10",
    SUM(CASE WHEN COHORT_MONTH = 'Month_11' THEN SALES ELSE 0 END) AS "MONTH_11",
    SUM(CASE WHEN COHORT_MONTH = 'Month_12' THEN SALES ELSE 0 END) AS "MONTH_12"
FROM CTE2
GROUP BY FIRST_TRANSACTION_MONTH
ORDER BY FIRST_TRANSACTION_MONTH;


